# Generated by Django 5.1.4 on 2025-01-05 19:41

import django.db.models.deletion
import django.utils.timezone
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100, verbose_name='Title')),
                ('Description', models.TextField(max_length=10000, verbose_name='Description')),
                ('CreatedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('Image', models.ImageField(upload_to='BlogPost/', verbose_name='Image')),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BlogPost_author', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('Tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='BlogPost_Category', to='Blog.category', verbose_name='Category')),
            ],
        ),
    ]
