# Generated by Django 5.1.4 on 2025-01-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('site_logo', models.ImageField(upload_to='Settings/')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('descreption', models.TextField(max_length=300)),
                ('FB_link', models.URLField()),
                ('Twitter_link', models.URLField()),
                ('Instagram_link', models.URLField()),
            ],
        ),
    ]
