# Generated by Django 5.1.4 on 2025-01-07 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0002_property_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='Slug',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='propertyimages',
            name='Property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Property_Image', to='Property.property'),
        ),
    ]
