# Generated by Django 5.1.4 on 2025-01-08 10:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0003_rename_slug_property_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='Description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
