# Generated by Django 5.1.4 on 2025-01-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0004_alter_property_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='Description',
            field=models.TextField(max_length=10000),
        ),
    ]
