# Generated by Django 4.2.18 on 2025-01-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0006_alter_propertybooking_children_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertybooking',
            name='Children',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
        migrations.AlterField(
            model_name='propertybooking',
            name='Guests',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')]),
        ),
    ]
