# Generated by Django 5.1.4 on 2025-01-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Property', '0009_alter_propertybooking_children_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Icon',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
